morethanmin/morethan-log

- src/components/Layout/Header/index.jsx
- src/components/Theme.jsx
- src/containers/Feed/components/Tags.jsx
- src/styles/globals.css
PR for the following changes. 
1. Enabling Dark Mode. [ Issue #20 ]
2. Removing the Horizontal scroll bar for Tags in Desktop view.
Now Horizontal scroll bar wont be visible for desktop view, but only for mobile view.
> Enabling Dark Mode

- next.config.js
Fix the list below.
- #57  
- #66
> [FIX] Adding image domain

- package.json
- src/containers/PostDetail/index.tsx
- yarn.lock
support mermaid Digram 
https://github.com/morethanmin/morethan-log/issues/77
> FEAT : support mermaid digram 

- src/containers/Detail/components/PostDetail/PostHeader.tsx
- src/types/index.ts
Corrected the error that may occur if there is no picture in the notion profile.
If user don't have a profile picture, the avatar.svg to be showed.
https://github.com/morethanmin/morethan-log/issues/91
> [FIX] no notion profile photo error

- README.md
- package.json
- site.config.js
- src/components/Cusdis.tsx
- src/containers/Detail/components/PostDetail/CommentBox.tsx
- yarn.lock
- Add [Cusdis Comment](https://github.com/djyde/cusdis) support.
- Users can set their own cusdis in `site.config.js`.
- Using [official SDK](https://github.com/Cusdis/sdk/tree/master/packages/react-cusdis).
https://github.com/morethanmin/morethan-log/issues/95
> [FEAT] add cusdis comment support

- src/containers/Feed/components/lists/TagList.tsx
- src/containers/Feed/index.tsx
- src/hooks/useThemeEffect.ts
- tsconfig.json
- fixed typo about path of tsconfig.json
- `@custeomTypes` -> `@customTypes`
> FIX: fix typo

- src/libs/utils/notion/filterPosts.ts
- src/types/index.ts
I fixed typo
`TPostStstus -> TPostStatus`
https://github.com/morethanmin/morethan-log/issues/XX
> [FIX]: fix typo (TPostStatus)

- site.config.js
- src/components/Layout/Header/NavBar.tsx
- src/components/Layout/Header/index.tsx
- src/containers/Feed/components/cards/ProfileCard.tsx
- src/containers/Feed/components/lists/TagList.tsx
- src/containers/Feed/index.tsx
- src/styles/globals.css
> [FEAT] adding sticky section

- README.md
Add user guide in english
see discussion #89
> [DOCUMENTATION] Add user guide in readme.md (in English)

- src/layouts/RootLayout/ThemeProvider/Global/index.tsx
- src/routes/Feed/PostList/PostCard.tsx
https://github.com/morethanmin/morethan-log/issues/XX
> [FIX] post card ui issue

- src/routes/Detail/PostDetail/CommentBox/Utterances.tsx
- src/routes/Detail/PostDetail/CommentBox/index.tsx
- src/routes/Detail/components/NotionRenderer/index.tsx
comment darkmode
https://github.com/morethanmin/morethan-log/issues/XX
> [FIX] comment darkmode

- src/components/Category/constants.ts
Fix the color set code to use a record
https://github.com/morethanmin/morethan-log/issues/XX
> FIX :: color set code to use record

- site.config.js
made to use "" if process.env.NEXT_PUBLIC_UTTERANCES_REPO doesn't exist
https://github.com/morethanmin/morethan-log/issues/#271
> [FIX] change utterances value

- README.md
- site.config.js
- src/pages/_document.tsx
I added naver site veriifcation feature.
I tested it on the local environment and vercel.
#239
> feat: naver site verification

- README.md
- site.config.js
Adding clarification to docs for setting environment variables, as I among other users ran into build errors when we pasted the entire notion page URL into the NOTION_PAGE_ID. Clarifying instructions for this will help users be able to use the repo.
https://github.com/morethanmin/morethan-log/issues/207
https://github.com/morethanmin/morethan-log/discussions/221
- [ x] I have read the [Contributing Guide](./docs/CONTRIBUTING.md)
- [x ] I have written documents and tests, if needed.
> fix: clarify docs for build 'value' error

- src/routes/Detail/PostDetail/CommentBox/Utterances.tsx
I refactored the existing codebase, replacing the { [key: string]: string } type notation with the more concise and TypeScript-specific Record<string, string> type. This change is aimed at enhancing code readability and leveraging TypeScript's advanced type capabilities for better type checking and maintainability.
I propose that this refactor be merged into our main codebase. The use of Record<string, string> not only simplifies our type definitions but also aligns with best practices in TypeScript for handling homogenous types. This change will make our code more robust and easier to understand, especially for new developers joining the project. Additionally, this modification paves the way for further improvements in our type system and overall code quality. …
> FIX :: utterances config to use record

- .github/CONTRIBUTING.md
- Dockerfile
- Makefile
- Create a Dockerfile to easily set up a local development environment.
- The docker command is long, so we made it easy to execute with a Makefile.
- setup target 
- Build docker image.
- Library Installation.
- Create .env.local file with NOTION_PAGE_ID.
- dev target
- Run `yarn run dev`.
- run target
- It goes inside the container.
- Write how to build a development environment using docker.
Here is a screenshot of the browser open.
Not exists. If you need it, I'll make it🙏
> Fix: Create Dockerfile and Makefile for use in the local environment

- .github/CONTRIBUTING.md
- README.md
Added Q&A
no ticket, just write the document.
> [docs]: update README.md and CONTRIBUTING.md

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/PULL_REQUEST_TEMPLATE.md
- README.md
> [docs]: edit link

- site.config.js
- src/hooks/useScheme.ts
- src/layouts/RootLayout/ThemeProvider/index.tsx
- src/routes/Detail/PostDetail/CommentBox/Utterances.tsx
- src/styles/theme.ts
- src/types/index.ts
- The scattered `Scheme` type declaration was integrated into the `src/types/index.ts` path. 345da8991f2223be563d897407b92933debf50a4
- `Scheme` has been integrated and the ternary operation has been removed as it is unnecessary. 4cc70c0af57191d582d238c2f18f57eca9858125
- Added `scheme` property to set blog theme to `site.config.js` file. 259efc013ce2d222bda7b985ba43e7cbe02cf2bf
- Added `followSystemTheme` property that change themes based on system settings 4b4a0d0f2d75f4eca78879880ded004cb22dc806
<br>
[site.config.js #L23-24](https://github.com/nfl1ryxditimo12/morethan-log/blob/4b4a0d0f2d75f4eca78879880ded004cb22dc806/site.config.js#L23-L24)
> 1. If you want to choose `light` mode as the default theme, please write that. default value is `dark`.
>
> 2. If `followSystemTheme` is true, …
> [feat, refactor]: Support to config default theme

- package.json
- src/routes/Detail/hooks/useMermaidEffect.ts
- src/routes/Detail/index.tsx
- yarn.lock
This pull request improves the rendering logic of Mermaid diagrams, adds support for dynamic dark and light themes, and applies CSS styling based on the current theme. It also includes logic to wait for Mermaid initialization and the presence of HTML elements with the language-mermaid class.
1. Updated Mermaid version from ^9.3.0 to ^10.9.1.
2. Improved Mermaid Rendering Logic:
Added useMermaidEffect hook to initialize Mermaid with either dark or default theme based on Scheme.
Applied animations for smooth transitions when rendering Mermaid diagrams.
3. Added CSS Styling:
Applied theme-based background color to Mermaid code blocks.
- The changes were tested focusing on the initial render and reusing Mermaid code inside \<PRE> tags without issues.
- Example: …
> enhance Mermaid rendering and styling with theme support
